"""
Shader program metadata - what each shader ACTUALLY uses.

Nufx.db answers "which parameters does this shader program require?". That is
the nufxlb's own list, and it is the right question when building a matl entry:
a required param that is missing gets zeroed by the game.

This module answers a different question - "which of those does the shader
code actually read, and through which channels?" - by shipping the shader info
dump from Smush-Material-Research, which was generated by analysing the
decompiled shader source. The two lists usually agree in length, but only this
one knows that SFX_PBS_0100000008008269 reads CustomVector0.x and ignores
.yzw, or that a given program never touches the lighting it was handed.

Data: shader_file/shader_info.json.gz, 4008 programs, ~57KB on disk. Repacked
from Value Dumps/shader_info_v13.0.1.7z with the field names shortened; see
FIELD_MAP below for the mapping back to the names used in the original dump.

This supersedes shaders_discard_v13.0.1.txt, which was one boolean column
(`discard`) of this same data set.
"""

import gzip
import json
from pathlib import Path

# Short key -> what it meant in the original shader_info.json dump.
FIELD_MAP = {
    'd': 'discard',
    'p': 'premultiplied',
    'r': 'receives_shadow',
    's': 'sh',
    'l': 'lighting',
    'c': 'complexity',
    'a': 'attrs',
    'm': 'params',
}

# Length of a shader label with no render pass tag, e.g. SFX_PBS_0100000008008269.
_BASE_LABEL_LEN = len('SFX_PBS_0100000008008269')

RENDER_PASSES = ('_opaque', '_far', '_sort', '_near')

_cache = None
_usage_cache = None


def _data_file(name):
    return Path(__file__).parent.joinpath('shader_file', name).resolve()


def _load():
    """Parse the gzipped dump once and keep it for the session."""
    global _cache
    if _cache is None:
        try:
            with gzip.open(_data_file('shader_info.json.gz'), 'rt', encoding='utf-8') as f:
                _cache = json.load(f)['shaders']
        except Exception as e:
            print(f'[sub_matl] Could not read shader info dump: {e}')
            _cache = {}
    return _cache


def _load_usage():
    """How often each shader program is used by the shipped game.

    Counted from the vanilla material dump (Smush-Material-Research
    materials_v13.0.1.db): 203 distinct programs across fighter models, 2380
    across everything. Search ranks by this first, because "cheapest shader
    that technically has the right textures" is almost never the answer you
    want - that picks obscure stage and effect programs over the handful of
    programs fighters are actually built from.
    """
    global _usage_cache
    if _usage_cache is None:
        try:
            with gzip.open(_data_file('shader_usage.json.gz'), 'rt', encoding='utf-8') as f:
                _usage_cache = json.load(f)
        except Exception as e:
            print(f'[sub_matl] Could not read shader usage table: {e}')
            _usage_cache = {'fighter': {}, 'all': {}}
    return _usage_cache


def fighter_usage_count(shader_label):
    """How many vanilla fighter materials use this shader program."""
    return _load_usage()['fighter'].get(base_label(shader_label), 0)


def total_usage_count(shader_label):
    """How many vanilla materials of any kind use this shader program."""
    return _load_usage()['all'].get(base_label(shader_label), 0)


def base_label(shader_label):
    """Drop the render pass tag: 'SFX_..._opaque' -> 'SFX_...'.

    The dump is keyed by program, and every render pass variant of a program
    shares its shader code, so the tag is not part of the lookup key.
    """
    if not shader_label:
        return ''
    return shader_label[:_BASE_LABEL_LEN]


def render_pass_of(shader_label):
    """The '_opaque' / '_far' / '_sort' / '_near' tag, or '' if untagged."""
    for suffix in RENDER_PASSES:
        if shader_label.endswith(suffix):
            return suffix
    return ''


def with_render_pass(shader_label, render_pass):
    """Same program, different render pass tag."""
    return base_label(shader_label) + render_pass


def get(shader_label):
    """Raw record for a shader label, or None when it isn't in the dump."""
    return _load().get(base_label(shader_label))


def exists(shader_label):
    return get(shader_label) is not None


# -- Flags --------------------------------------------------------------------
# Each returns `default` when the label is unknown, so a caller that hasn't
# validated its label still gets the safe answer rather than an exception.

def _flag(shader_label, key, default=False):
    info = get(shader_label)
    if info is None:
        return default
    return bool(info.get(key, default))


def is_discard(shader_label):
    """True when the shader alpha-tests (discards fragments)."""
    return _flag(shader_label, 'd')


def is_premultiplied(shader_label):
    """True when the shader outputs premultiplied alpha.

    Such a shader must not also be given a Source Color blend factor of
    SourceAlpha, or alpha gets applied twice.
    """
    return _flag(shader_label, 'p')


def receives_shadow(shader_label):
    return _flag(shader_label, 'r')


def has_spherical_harmonics(shader_label):
    return _flag(shader_label, 's')


def is_lighting(shader_label):
    """False for shadeless shaders, whose output ignores scene lighting."""
    return _flag(shader_label, 'l')


def complexity(shader_label):
    """Relative cost, 0.0 to 1.0. Used to prefer the cheapest adequate shader."""
    info = get(shader_label)
    return float(info.get('c', 0.0)) if info else 0.0


# -- Parameters ---------------------------------------------------------------
# Entries in the dump look like 'CustomVector13.xyzw', 'Texture0' or
# 'CustomVector0.x' - a bare name when the param has no channels, and a
# dot-suffixed channel mask otherwise.

def _split(entry):
    name, _, channels = entry.partition('.')
    return name, channels


def used_params(shader_label):
    """Every param name the shader code reads, without channel suffixes."""
    info = get(shader_label)
    if info is None:
        return set()
    return {_split(entry)[0] for entry in info.get('m', ())}


def uses_param(shader_label, param_name):
    return param_name in used_params(shader_label)


def used_channels(shader_label, param_name):
    """Which of 'xyzw' the shader reads from a param.

    Returns '' for a param with no channels (a texture, say), and None when
    the shader doesn't use the param at all. An empty string and None mean
    different things here, so callers should test against None explicitly.
    """
    info = get(shader_label)
    if info is None:
        return None
    for entry in info.get('m', ()):
        name, channels = _split(entry)
        if name == param_name:
            return channels
    return None


def used_textures(shader_label):
    """Just the Texture* params, e.g. {'Texture0', 'Texture4', 'Texture6'}."""
    return {p for p in used_params(shader_label) if p.startswith('Texture')}


# -- Vertex attributes --------------------------------------------------------

def used_attributes(shader_label):
    """Attribute names the shader reads, e.g. {'map1', 'colorSet1'}."""
    info = get(shader_label)
    if info is None:
        return set()
    return {_split(entry)[0] for entry in info.get('a', ())}


def attribute_channels(shader_label, attribute_name):
    """Which channels of a vertex attribute the shader reads, or None."""
    info = get(shader_label)
    if info is None:
        return None
    for entry in info.get('a', ()):
        name, channels = _split(entry)
        if name == attribute_name:
            return channels
    return None


# -- Search -------------------------------------------------------------------

def find_shader_labels(
    *,
    textures=(),
    exclude_textures=(),
    attributes=(),
    lighting=None,
    discard=None,
    premultiplied=None,
    exact_textures=False,
    fighter_only=True,
    limit=25,
):
    """Shader programs matching a feature set, best match first.

    Ranked by how heavily vanilla fighters use the program, then by ascending
    complexity as the tie-break. Ranking on complexity alone looks reasonable
    but returns junk - the cheapest program with a given texture set is
    typically some one-off stage or effect shader, not one of the ~200
    programs every fighter in the game is actually built from.

    Every filter is optional; passing none returns the whole dump ranked as
    above. Boolean filters are three-state - None means "don't care".

    textures / attributes
        Names the shader must use, e.g. textures=('Texture0', 'Texture6').
    exclude_textures
        Names the shader must NOT use. Handy for finding the plain variant of
        a shader, e.g. excluding Texture5 to rule out the emissive versions.
    exact_textures
        Require the shader's texture set to be exactly `textures`, rather than
        a superset. Cube maps (Texture2/7/8) are ignored for this comparison,
        since almost every lit fighter shader takes a specular cube map and
        callers are really asking about the maps they have to author.
    fighter_only
        Only consider programs some vanilla fighter uses. On by default - this
        is a fighter modding workflow, and the other ~3800 programs are stage,
        effect and UI shaders that will not behave on a character model.

    Returns a list of base labels (no render pass tag) - pass through
    with_render_pass() to get something a material can actually use.
    """
    textures = set(textures)
    exclude_textures = set(exclude_textures)
    attributes = set(attributes)
    cube_maps = {'Texture2', 'Texture7', 'Texture8'}
    usage = _load_usage()['fighter']

    matches = []
    for label, info in _load().items():
        fighter_uses = usage.get(label, 0)
        if fighter_only and not fighter_uses:
            continue
        params = {_split(e)[0] for e in info.get('m', ())}
        shader_textures = {p for p in params if p.startswith('Texture')}

        if not textures.issubset(shader_textures):
            continue
        if exclude_textures & shader_textures:
            continue
        if exact_textures and (shader_textures - cube_maps) != (textures - cube_maps):
            continue
        if attributes:
            attrs = {_split(e)[0] for e in info.get('a', ())}
            if not attributes.issubset(attrs):
                continue
        if lighting is not None and bool(info.get('l')) != lighting:
            continue
        if discard is not None and bool(info.get('d')) != discard:
            continue
        if premultiplied is not None and bool(info.get('p')) != premultiplied:
            continue

        # Most-used first, then cheapest.
        matches.append((-fighter_uses, info.get('c', 0.0), label))

    matches.sort()
    return [label for _, _, label in matches[:limit]]


def describe(shader_label):
    """One-line human summary of a shader, for tooltips and reports."""
    info = get(shader_label)
    if info is None:
        return f'{shader_label} (not in shader database)'

    textures = sorted(used_textures(shader_label),
                      key=lambda t: int(t.replace('Texture', '')))
    bits = []
    bits.append('lit' if info.get('l') else 'shadeless')
    if info.get('d'):
        bits.append('alpha test')
    if info.get('p'):
        bits.append('premultiplied')
    if info.get('r'):
        bits.append('receives shadow')
    return f'{base_label(shader_label)}: {", ".join(bits)} | {", ".join(textures) or "no textures"}'
